import { NextRequest, NextResponse } from 'next/server';
import { sendMail } from '@/lib/mail';

// Basic rate-limit (in-memory) – resets on server restart.
const recent = new Map<string, number>();

export async function POST(req: NextRequest) {
  try {
    const ip = req.headers.get('x-forwarded-for')?.split(',')[0]?.trim() || 'unknown';
    const now = Date.now();
    const last = recent.get(ip) || 0;
    if (now - last < 4000) {
      return NextResponse.json({ error: 'Too many requests, slow down.' }, { status: 429 });
    }
    recent.set(ip, now);

    const body = await req.json();
    const { name, email, subject, message } = body || {};
    if (!name || !email || !subject || !message) {
      return NextResponse.json({ error: 'Missing fields' }, { status: 400 });
    }

    const adminTo = process.env.CONTACT_TO || process.env.MAIL_TO || 'shanuchahal37@gmail.com';

    try {
      const displayFrom = name ? `${escapeHeaderDisplay(name)} <${escapeHeaderEmail(email)}>` : escapeHeaderEmail(email);
      await sendMail({
        to: adminTo,
        subject: `[Contact] ${subject}`,
        replyTo: email,
        from: displayFrom,
        html: `<!DOCTYPE html><html><body style="font-family:Arial,sans-serif;line-height:1.6;">
          <h2 style="color:#0f172a;margin:0 0 8px;">New Contact Message</h2>
          <p><strong>Name:</strong> ${escapeHtml(name)}</p>
          <p><strong>Email:</strong> ${escapeHtml(email)}</p>
          <p><strong>Subject:</strong> ${escapeHtml(subject)}</p>
          <p><strong>Message:</strong><br/>${escapeHtml(message).replace(/\n/g,'<br/>')}</p>
          <hr style="margin:24px 0;"/>
          <p style="font-size:12px;color:#64748b;">This email was generated by the contact form on soloyolo.in</p>
        </body></html>`
      });
    } catch (mailErr: unknown) {
      const message = mailErr instanceof Error ? mailErr.message : '';
      const isMissing = /Mail transport env vars missing/i.test(message);
      if (isMissing && process.env.NODE_ENV !== 'production') {
        console.warn('[contact] Mail vars missing; returning dev fallback success.');
        return NextResponse.json({ ok: true, devFallback: true });
      }
      throw mailErr instanceof Error ? mailErr : new Error('Unknown mail error');
    }

    return NextResponse.json({ ok: true });
  } catch (err: unknown) {
    console.error('Contact form error', err);
    return NextResponse.json({ error: 'Internal error' }, { status: 500 });
  }
}

function escapeHtml(str: string): string {
  return str.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c] || c));
}

function escapeHeaderEmail(str: string) {
  return str.replace(/[\r\n<>"']/g, '').trim();
}
function escapeHeaderDisplay(str: string) {
  return str.replace(/[\r\n<>"']/g, ' ').trim();
}
